# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Craftybase < Formula
  desc "Official CLI for the Craftybase Public API"
  homepage "https://craftybase.com"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/craftybase/craftybase-cli/releases/download/v0.2.0/craftybase_0.2.0_darwin_amd64.tar.gz"
      sha256 "3bef85999705da3a6fceed3370b504a012b1fde7349012dc7b23bfa438b3ad8e"

      define_method(:install) do
        bin.install "craftybase"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/craftybase/craftybase-cli/releases/download/v0.2.0/craftybase_0.2.0_darwin_arm64.tar.gz"
      sha256 "13058b1aa0b39827c198ea63994173c17ba3e6650b818345abb7ca2c15a95b33"

      define_method(:install) do
        bin.install "craftybase"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/craftybase/craftybase-cli/releases/download/v0.2.0/craftybase_0.2.0_linux_amd64.tar.gz"
      sha256 "a3f268ff98bf1ace94c23ef45c8fc5b3552805d5a9c3c01fcea2a253a55474fa"
      define_method(:install) do
        bin.install "craftybase"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/craftybase/craftybase-cli/releases/download/v0.2.0/craftybase_0.2.0_linux_arm64.tar.gz"
      sha256 "5294d827da8cb64b1430c34c612ec19a3bde353f97ab7bfb2476fef7a839aaf7"
      define_method(:install) do
        bin.install "craftybase"
      end
    end
  end

  test do
    system "#{bin}/craftybase version"
  end
end
