# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Craftybase < Formula
  desc "Official CLI for the Craftybase Public API"
  homepage "https://craftybase.com"
  version "0.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/craftybase/craftybase-cli/releases/download/v0.3.0/craftybase_0.3.0_darwin_amd64.tar.gz"
      sha256 "2dc3794bd7c6dfd2232759d0d96405693c9167c02552b2b1070aa30c12ee9e19"

      define_method(:install) do
        bin.install "craftybase"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/craftybase/craftybase-cli/releases/download/v0.3.0/craftybase_0.3.0_darwin_arm64.tar.gz"
      sha256 "d1eb4d9790f3cb124b361ef7a8868ca1e237ef2da37de831e39ba3aef76506c1"

      define_method(:install) do
        bin.install "craftybase"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/craftybase/craftybase-cli/releases/download/v0.3.0/craftybase_0.3.0_linux_amd64.tar.gz"
      sha256 "5fa07b8b5c75e75a6590167ef8bb3033ba963b19893c0b9c54da34c12f205a2c"
      define_method(:install) do
        bin.install "craftybase"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/craftybase/craftybase-cli/releases/download/v0.3.0/craftybase_0.3.0_linux_arm64.tar.gz"
      sha256 "d420a4e9c8db4f6dd50c1ff0ec963b4b297f4d06d4a96acc1ec90d67a16c75a0"
      define_method(:install) do
        bin.install "craftybase"
      end
    end
  end

  test do
    system "#{bin}/craftybase version"
  end
end
