# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stocksmith < Formula
  desc "Official CLI for the Stocksmith Public API"
  homepage "https://cli.stocksmith.dev"
  version "0.4.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/craftybase/stocksmith-cli/releases/download/v0.4.0/stocksmith_0.4.0_darwin_amd64.tar.gz"
      sha256 "8398427092f7f199ec4e8ccd68b01c86fa49e55447d939269f1e3b7fe87ca4c8"

      define_method(:install) do
        bin.install "stocksmith"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/craftybase/stocksmith-cli/releases/download/v0.4.0/stocksmith_0.4.0_darwin_arm64.tar.gz"
      sha256 "10ca539a79f7d50ec06c93e1bd0a9831352ec84d8ca738cb0bbcf8ee6adc27a1"

      define_method(:install) do
        bin.install "stocksmith"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/craftybase/stocksmith-cli/releases/download/v0.4.0/stocksmith_0.4.0_linux_amd64.tar.gz"
      sha256 "c417b0d2d974cc0f1fcec2420d61dbeaea2410a72d4542e358778c8a8d915783"
      define_method(:install) do
        bin.install "stocksmith"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/craftybase/stocksmith-cli/releases/download/v0.4.0/stocksmith_0.4.0_linux_arm64.tar.gz"
      sha256 "914c99b57751c8cd5b9a474fa3486a37dd296350777cf994bc7c1677d04b7f5a"
      define_method(:install) do
        bin.install "stocksmith"
      end
    end
  end

  test do
    system "#{bin}/stocksmith version"
  end
end
